name: Deploy PHP App to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo, pdo_mysql
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Zip application for Elastic Beanstalk
        run: zip -r PhpApp.zip . -x '*.git*'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          application_name: PhpApp
          environment_name: PhpApp-env
          version_label: ${{ github.sha }}
          region: us-east-1
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          existing_bucket_name: elasticbeanstalk-us-east-1-663136559298
          deployment_package: PhpApp.zip

